import os
import json
import yaml
from datetime import datetime

# Load tool information from the tools_details.yml
with open(r'tools_details.yml') as file:
    tools = yaml.load(file, Loader=yaml.FullLoader).get('tools')

def recurse_dir(path, level, total_case_catch_stats, is_root):
    results = ""

    found_sub_categories = False
    for subdir in sorted(os.listdir(path)):
        if os.path.isdir(os.path.join(path, subdir)) and not os.path.exists(os.path.join(path, subdir, "main.tf")):
            found_sub_categories = True

            results += recurse_dir(os.path.join(path, subdir), level + 1, total_case_catch_stats, is_root = False)

    if not found_sub_categories:
        results += f'### {path}\n'
        results += generate_category_test_case_table(path, total_case_catch_stats)

    return results

def generate_category_test_case_table(path, total_case_catch_stats):
    results = ""
    category_catch_summary = {x.get('id'): 0 for x in tools}
    category_catch_summary['total'] = 0

    header = "| Test Case |"
    header_line = "|----|"
    for tool in tools:
        header += f" {tool.get('name')} |"
        header_line += "----|"
    results += f"{header}\n"
    results += f"{header_line}\n"
    for subdir in sorted(os.listdir(path)):

        summary_json_path = os.path.join(path, subdir, "results_summary.json")
        if os.path.exists(summary_json_path):
            category_catch_summary['total'] += 1
            total_case_catch_stats['total'] += 1

            with open(summary_json_path) as summary_json_file:
                summary_json = json.load(summary_json_file)
                adjusted_case_name = (subdir[:40] + '..') if len(subdir) > 40 else subdir
                case_line = f"|[{adjusted_case_name}]({os.path.join(path, subdir)})|"

                for tool in tools:
                    case_line += (':white_check_mark:' if summary_json[tool.get('id')] == 'yes' else ':x:') + "|"
                    category_catch_summary[tool.get('id')] += 1 if summary_json[tool.get('id')] == 'yes' else 0
                    total_case_catch_stats[tool.get('id')] += 1 if summary_json[tool.get('id')] == 'yes' else 0

                results += f"{case_line}\n"

    # Skip categories still in construction (no result summaries)
    if category_catch_summary['total'] > 0:
        summary_line = f"|Category Catch Rate|"
        for tool in tools:
            summary_line += f"{round(category_catch_summary[tool.get('id')] * 100 / category_catch_summary['total'])}%|"
        results += f"{summary_line}\n\n"

    return results


def generate_summary_table():
    header = "|     |"
    header_line = "|----|"
    for tool in tools:
        header += f" {tool.get('name')} |"
        header_line += "----|"

    results = f"### Summary\n"
    results += f"Last update: {datetime.today().strftime('%Y-%m-%d')}\n\n"
    results += f"{header}\n"
    results += f"{header_line}\n"

    version_line = f"|Tested Version|"
    for tool in tools:
        with open(f"version_{tool.get('id')}.txt") as fp:
            tool_version = fp.readline().strip().replace("v", "")
            version_line += f"{tool_version}|"
    results += f"{version_line}\n"

    summary_line = f"|Total Catch Rate|"
    for tool in tools:
        summary_line += f"{round(total_case_catch_stats[tool.get('id')] * 100 / total_case_catch_stats['total'])}%|"
    results += f"{summary_line}\n"

    return results

def generate_tools_table():
    header = "|     |"
    header_line = "|----|"
    for tool in tools:
        header += f" [{tool.get('name')}]({tool.get('main_link')}) |"
        header_line += "----|"

    results = ""
    results += f"{header}\n"
    results += f"{header_line}\n"

    license_line = f"|License|"
    for tool in tools:
        license_line += f"{tool.get('license')}|"
    results += f"{license_line}\n"

    custom_rules_line = f"|Custom Rules|"
    for tool in tools:
        custom_rules_line += f"{tool.get('custom_rules')}|"
    results += f"{custom_rules_line}\n"

    return results


if __name__ == "__main__":
    total_case_catch_stats = {x.get('id'): 0 for x in tools}
    total_case_catch_stats['total'] = 0

    full_results = recurse_dir("test-cases", 2, total_case_catch_stats, is_root = True)

    with open("resources/README.md.template", "r") as fr:
        template = "[comment]: <> (DO NOT EDIT THIS FILE, EDIT README.md.template INSTEAD)\n"
        template += fr.read()

    template = template.replace("{{ tools_table }}", generate_tools_table())
    template = template.replace("{{ summary_table }}", generate_summary_table())
    template = template.replace("{{ full_results }}", full_results)
    
    with open("README.md", "w") as fw:
        fw.write(template)

    print ("README.md updated")